const baseUrl = 'https://penman.mathlander';

export const defaultDate = new Date(1970, 0, 0);

export const apiConstants = {
    baseUrl: baseUrl,
    ping: `${baseUrl}/api/ping`,
    usersController: `${baseUrl}/api/users`,
    booksController: `${baseUrl}/api/books`,
    chaptersController: `${baseUrl}/api/chapters`,
    personificationsController: `${baseUrl}/api/personifications`,
    promptsController: `${baseUrl}/api/prompts`,
    relationshipsController: `${baseUrl}/api/relationships`,
    shortsController: `${baseUrl}/api/shorts`,
    tagsController: `${baseUrl}/api/tags`,
    // collaborationsController: `${baseUrl}/api/collaborations`,
    penmanHub: `${baseUrl}/hubs/penman`,
    timeout: 5 * 1000,
};

export const authConstants = {
    AUTH_LOCAL_STORAGE_KEY: 'AUTH_LOCAL_STORAGE',
    AUTH_CLEAR_ERROR: 'AUTH_CLEAR_ERROR',

    CANCEL_AUTH_ACTION: 'CANCEL_AUTH_ACTION',

    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROR',

    LOGOUT: 'LOGOUT',

    REFRESH_TOKEN: 'REFRESH_TOKEN',
    REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',
    REFRESH_TOKEN_ERROR: 'REFRESH_TOKEN_ERROR',
    REFRESH_TOKEN_TIMEOUT: 'REFRESH_TOKEN_TIMEOUT',

    CREATE_NEW_USER:  'CREATE_NEW_USER',
    CREATE_NEW_USER_SUCCESS: 'CREATE_NEW_USER_SUCCESS',
    CREATE_NEW_USER_ERROR: 'CREATE_NEW_USER_ERROR',
    CREATE_NEW_USER_TIMEOUT: 'CREATE_NEW_USER_TIMEOUT',

    UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
    UPDATE_USER_PROFILE_SUCCESS: 'UPDATE_USER_PROFILE_SUCCESS',
    UPDATE_USER_PROFILE_ERROR: 'UPDATE_USER_PROFILE_ERROR',
    UPDATE_USER_PROFILE_TIMEOUT: 'UPDATE_USER_PROFILE_TIMEOUT',

    UPDATE_USER_PASSWORD: 'UPDATE_USER_PASSWORD',
    UPDATE_USER_PASSWORD_SUCCESS: 'UPDATE_USER_PASSWORD_SUCCESS',
    UPDATE_USER_PASSWORD_ERROR: 'UPDATE_USER_PASSWORD_ERROR',
    UPDATE_USER_PASSWORD_TIMEOUT: 'UPDATE_USER_PASSWORD_TIMEOUT',

    DEACTIVATE_USER_ACCOUNT: 'DEACTIVATE_USER_ACCOUNT',
    DEACTIVATE_USER_ACCOUNT_SUCCESS: 'DEACTIVATE_USER_ACCOUNT_SUCCESS',
    DEACTIVATE_USER_ACCOUNT_ERROR: 'DEACTIVATE_USER_ACCOUNT_ERROR',
    DEACTIVATE_USER_ACCOUNT_TIMEOUT: 'DEACTIVATE_USER_ACCOUNT_TIMEOUT',
};

export const dashboardConstants = {
    VISIT_RECENT_ITEM: 'VISIT_RECENT_ITEM',
    VISIT_RECENT_ITEM_CLEAR: 'VISIT_RECENT_ITEM_CLEAR',
};

export const bookConstants = {
    BOOK_LOCAL_STORAGE_KEY: 'BOOK_LOCAL_STORAGE_KEY',
    BOOK_CLEAR_ERROR: 'BOOK_CLEAR_ERROR',

    CANCEL_BOOK_ACTION: 'CANCEL_BOOK_ACTION',

    CREATE_NEW_BOOK: 'CREATE_NEW_BOOK',
    CREATE_NEW_BOOK_SUCCESS: 'CREATE_NEW_BOOK_SUCCESS',
    CREATE_NEW_BOOK_ERROR: 'CREATE_NEW_BOOK_ERROR',
    CREATE_NEW_BOOK_TIMEOUT: 'CREATE_NEW_BOOK_TIMEOUT',

    READ_ALL_BOOKS: 'READ_ALL_BOOKS',
    READ_ALL_BOOKS_SUCCESS: 'READ_ALL_BOOKS_SUCCESS',
    READ_ALL_BOOKS_ERROR: 'READ_ALL_BOOKS_ERROR',
    READ_ALL_BOOKS_TIMEOUT: 'READ_ALL_BOOKS_TIMEOUT',

    READ_BOOK: 'READ_BOOK',
    READ_BOOK_SUCCESS: 'READ_BOOK_SUCCESS',
    READ_BOOK_ERROR: 'READ_BOOK_ERROR',
    READ_BOOK_TIMEOUT: 'READ_BOOK_TIMEOUT',

    UPDATE_BOOK: 'UPDATE_BOOK',
    UPDATE_BOOK_SUCCESS: 'UPDATE_BOOK_SUCCESS',
    UPDATE_BOOK_ERROR: 'UPDATE_BOOK_ERROR',
    UPDATE_BOOK_TIMEOUT: 'UPDATE_BOOK_TIMEOUT',

    DELETE_BOOK: 'DELETE_BOOK',
    DELETE_BOOK_SUCCESS: 'DELETE_BOOK_SUCCESS',
    DELETE_BOOK_ERROR: 'DELETE_BOOK_ERROR',
    DELETE_BOOK_TIMEOUT: 'DELETE_BOOK_TIMEOUT',
};

export const chapterConstants = {
    CHAPTER_LOCAL_STORAGE_KEY: 'CHAPTER_LOCAL_STORAGE',
    CHAPTER_CLEAR_ERROR: 'CHAPTER_CLEAR_ERROR',

    CANCEL_CHAPTER_ACTION: 'CANCEL_CHAPTER_ACTION',

    CREATE_NEW_CHAPTER: 'CREATE_NEW_CHAPTER',
    CREATE_NEW_CHAPTER_SUCCESS: 'CREATE_NEW_CHAPTER_SUCCESS',
    CREATE_NEW_CHAPTER_ERROR: 'CREATE_NEW_CHAPTER_ERROR',
    CREATE_NEW_CHAPTER_TIMEOUT: 'CREATE_NEW_CHAPTER_TIMEOUT',

    READ_ALL_CHAPTERS: 'READ_ALL_CHAPTERS',
    READ_ALL_CHAPTERS_SUCCESS: 'READ_ALL_CHAPTERS_SUCCESS',
    READ_ALL_CHAPTERS_ERROR: 'READ_ALL_CHAPTERS_ERROR',
    READ_ALL_CHAPTERS_TIMEOUT: 'READ_ALL_CHAPTERS_TIMEOUT',

    READ_CHAPTER: 'READ_CHAPTER',
    READ_CHAPTER_SUCCESS: 'READ_CHAPTER_SUCCESS',
    READ_CHAPTER_ERROR: 'READ_CHAPTER_ERROR',
    READ_CHAPTER_TIMEOUT: 'READ_CHAPTER_TIMEOUT',

    UPDATE_CHAPTER: 'UPDATE_CHAPTER',
    UPDATE_CHAPTER_SUCCESS: 'UPDATE_CHAPTER_SUCCESS',
    UPDATE_CHAPTER_ERROR: 'UPDATE_CHAPTER_ERROR',
    UPDATE_CHAPTER_TIMEOUT: 'UPDATE_CHAPTER_TIMEOUT',

    DELETE_CHAPTER: 'DELETE_CHAPTER',
    DELETE_CHAPTER_SUCCESS: 'DELETE_CHAPTER_SUCCESS',
    DELETE_CHAPTER_ERROR: 'DELETE_CHAPTER_ERROR',
    DELETE_CHAPTER_TIMEOUT: 'DELETE_CHAPTER_TIMEOUT',
};

export const personificationConstants = {
    PERSONIFICATION_LOCAL_STORAGE_KEY: 'PERSONIFICATION_LOCAL_STORAGE_KEY',
    PERSONIFICATION_CLEAR_ERROR: 'PERSONIFICATION_CLEAR_ERROR',

    CANCEL_PERSONIFICATION_ACTION: 'CANCEL_PERSONIFICATION_ACTION',

    CREATE_NEW_PERSONIFICATION: 'CREATE_NEW_PERSONIFICATION',
    CREATE_NEW_PERSONIFICATION_SUCCESS: 'CREATE_NEW_PERSONIFICATION_SUCCESS',
    CREATE_NEW_PERSONIFICATION_ERROR: 'CREATE_NEW_PERSONIFICATION_ERROR',
    CREATE_NEW_PERSONIFICATION_TIMEOUT: 'CREATE_NEW_PERSONIFICATION_TIMEOUT',

    READ_ALL_PERSONIFICATIONS: 'READ_ALL_PERSONIFICATIONS',
    READ_ALL_PERSONIFICATIONS_SUCCESS: 'READ_ALL_PERSONIFICATIONS_SUCCESS',
    READ_ALL_PERSONIFICATIONS_ERROR: 'READ_ALL_PERSONIFICATIONS_ERROR',
    READ_ALL_PERSONIFICATIONS_TIMEOUT: 'READ_ALL_PERSONIFICATIONS_TIMEOUT',

    READ_PERSONIFICATION: 'READ_PERSONIFICATION',
    READ_PERSONIFICATION_SUCCESS: 'READ_PERSONIFICATION_SUCCESS',
    READ_PERSONIFICATION_ERROR: 'READ_PERSONIFICATION_ERROR',
    READ_PERSONIFICATION_TIMEOUT: 'READ_PERSONIFICATION_TIMEOUT',

    UPDATE_PERSONIFICATION: 'UPDATE_PERSONIFICATION',
    UPDATE_PERSONIFICATION_SUCCESS: 'UPDATE_PERSONIFICATION_SUCCESS',
    UPDATE_PERSONIFICATION_ERROR: 'UPDATE_PERSONIFICATION_ERROR',
    UPDATE_PERSONIFICATION_TIMEOUT: 'UPDATE_PERSONIFICATION_TIMEOUT',

    DELETE_PERSONIFICATION: 'DELETE_PERSONIFICATION',
    DELETE_PERSONIFICATION_SUCCESS: 'DELETE_PERSONIFICATION_SUCCESS',
    DELETE_PERSONIFICATION_ERROR: 'DELETE_PERSONIFICATION_ERROR',
    DELETE_PERSONIFICATION_TIMEOUT: 'DELETE_PERSONIFICATION_TIMEOUT',
};

export const promptConstants = {
    PROMPT_LOCAL_STORAGE_KEY: 'PROMPT_LOCAL_STORAGE',
    PROMPT_CLEAR_ERROR: 'PROMPT_CLEAR_ERROR',

    CANCEL_PROMPT_ACTION: 'CANCEL_PROMPT_ACTION',

    CREATE_NEW_PROMPT: 'CREATE_NEW_PROMPT',
    CREATE_NEW_PROMPT_SUCCESS: 'CREATE_NEW_PROMPT_SUCCESS',
    CREATE_NEW_PROMPT_ERROR: 'CREATE_NEW_PROMPT_ERROR',
    CREATE_NEW_PROMPT_TIMEOUT: 'CREATE_NEW_PROMPT_TIMEOUT',

    READ_ALL_PROMPTS: 'READ_ALL_PROMPTS',
    READ_ALL_PROMPTS_SUCCESS: 'READ_ALL_PROMPTS_SUCCESS',
    READ_ALL_PROMPTS_ERROR: 'READ_ALL_PROMPTS_ERROR',
    READ_ALL_PROMPTS_TIMEOUT: 'READ_ALL_PROMPTS_TIMEOUT',

    READ_PROMPT: 'READ_PROMPT',
    READ_PROMPT_SUCCESS: 'READ_PROMPT_SUCCESS',
    READ_PROMPT_ERROR: 'READ_PROMPT_ERROR',
    READ_PROMPT_TIMEOUT: 'READ_PROMPT_TIMEOUT',

    UPDATE_PROMPT: 'UPDATE_PROMPT',
    UPDATE_PROMPT_SUCCESS: 'UPDATE_PROMPT_SUCCESS',
    UPDATE_PROMPT_ERROR: 'UPDATE_PROMPT_ERROR',
    UPDATE_PROMPT_TIMEOUT: 'UPDATE_PROMPT_TIMEOUT',

    DELETE_PROMPT: 'DELETE_PROMPT',
    DELETE_PROMPT_SUCCESS: 'DELETE_PROMPT_SUCCESS',
    DELETE_PROMPT_ERROR: 'DELETE_PROMPT_ERROR',
    DELETE_PROMPT_TIMEOUT: 'DELETE_PROMPT_TIMEOUT',
};

export const shortConstants = {
    SHORT_LOCAL_STORAGE_KEY: 'SHORT_LOCAL_STORAGE',
    SHORT_CLEAR_ERROR: 'SHORT_CLEAR_ERROR',

    CANCEL_SHORT_ACTION: 'CANCEL_SHORT_ACTION',

    CREATE_NEW_SHORT: 'CREATE_NEW_SHORT',
    CREATE_NEW_SHORT_SUCCESS: 'CREATE_NEW_SHORT_SUCCESS',
    CREATE_NEW_SHORT_ERROR: 'CREATE_NEW_SHORT_ERROR',
    CREATE_NEW_SHORT_TIMEOUT: 'CREATE_NEW_SHORT_TIMEOUT',

    READ_ALL_SHORTS: 'READ_ALL_SHORTS',
    READ_ALL_SHORTS_SUCCESS: 'READ_ALL_SHORTS_SUCCESS',
    READ_ALL_SHORTS_ERROR: 'READ_ALL_SHORTS_ERROR',
    READ_ALL_SHORTS_TIMEOUT: 'READ_ALL_SHORTS_TIMEOUT',

    READ_SHORT: 'READ_SHORT',
    READ_SHORT_SUCCESS: 'READ_SHORT_SUCCESS',
    READ_SHORT_ERROR: 'READ_SHORT_ERROR',
    READ_SHORT_TIMEOUT: 'READ_SHORT_TIMEOUT',

    UPDATE_SHORT: 'UPDATE_SHORT',
    UPDATE_SHORT_SUCCESS: 'UPDATE_SHORT_SUCCESS',
    UPDATE_SHORT_ERROR: 'UPDATE_SHORT_ERROR',
    UPDATE_SHORT_TIMEOUT: 'UPDATE_SHORT_TIMEOUT',

    DELETE_SHORT: 'DELETE_SHORT',
    DELETE_SHORT_SUCCESS: 'DELETE_SHORT_SUCCESS',
    DELETE_SHORT_ERROR: 'DELETE_SHORT_ERROR',
    DELETE_SHORT_TIMEOUT: 'DELETE_SHORT_TIMEOUT',
};

export const tagConstants = {
    TAG_LOCAL_STORAGE_KEY: 'TAG_LOCAL_STORAGE',
    TAG_CLEAR_ERROR: 'TAG_CLEAR_ERROR',

    CANCEL_TAG_ACTION: 'CANCEL_TAG_ACTION',

    CREATE_NEW_TAG: 'CREATE_NEW_TAG',
    CREATE_NEW_TAG_SUCCESS: 'CREATE_NEW_TAG_SUCCESS',
    CREATE_NEW_TAG_ERROR: 'CREATE_NEW_TAG_ERROR',
    CREATE_NEW_TAG_TIMEOUT: 'CREATE_NEW_TAG_TIMEOUT',

    READ_ALL_TAGS: 'READ_ALL_TAGS',
    READ_ALL_TAGS_SUCCESS: 'READ_ALL_TAGS_SUCCESS',
    READ_ALL_TAGS_ERROR: 'READ_ALL_TAGS_ERROR',
    READ_ALL_TAGS_TIMEOUT: 'READ_ALL_TAGS_TIMEOUT',

    READ_TAG: 'READ_TAG',
    READ_TAG_SUCCESS: 'READ_TAG_SUCCESS',
    READ_TAG_ERROR: 'READ_TAG_ERROR',
    READ_TAG_TIMEOUT: 'READ_TAG_TIMEOUT',

    UPDATE_TAG: 'UPDATE_TAG',
    UPDATE_TAG_SUCCESS: 'UPDATE_TAG_SUCCESS',
    UPDATE_TAG_ERROR: 'UPDATE_TAG_ERROR',
    UPDATE_TAG_TIMEOUT: 'UPDATE_TAG_TIMEOUT',

    DELETE_TAG: 'DELETE_TAG',
    DELETE_TAG_SUCCESS: 'DELETE_TAG_SUCCESS',
    DELETE_TAG_ERROR: 'DELETE_TAG_ERROR',
    DELETE_TAG_TIMEOUT: 'DELETE_TAG_TIMEOUT',
};

export const relationshipConstants = {
    RELATIONSHIP_LOCAL_STORAGE_KEY: 'RELATIONSHIP_LOCAL_STORAGE',
    RELATIONSHIP_CLEAR_ERROR: 'RELATIONSHIP_CLEAR_ERROR',

    CANCEL_RELATIONSHIP_ACTION: 'CANCEL_RELATIONSHIP_ACTION',

    CREATE_NEW_RELATIONSHIP: 'CREATE_NEW_RELATIONSHIP',
    CREATE_NEW_RELATIONSHIP_SUCCESS: 'CREATE_NEW_RELATIONSHIP_SUCCESS',
    CREATE_NEW_RELATIONSHIP_ERROR: 'CREATE_NEW_RELATIONSHIP_ERROR',
    CREATE_NEW_RELATIONSHIP_TIMEOUT: 'CREATE_NEW_RELATIONSHIP_TIMEOUT',

    READ_ALL_RELATIONSHIPS: 'READ_ALL_RELATIONSHIPS',
    READ_ALL_RELATIONSHIPS_SUCCESS: 'READ_ALL_RELATIONSHIPS_SUCCESS',
    READ_ALL_RELATIONSHIPS_ERROR: 'READ_ALL_RELATIONSHIPS_ERROR',
    READ_ALL_RELATIONSHIPS_TIMEOUT: 'READ_ALL_RELATIONSHIPS_TIMEOUT',

    READ_RELATIONSHIP: 'READ_RELATIONSHIP',
    READ_RELATIONSHIP_SUCCESS: 'READ_RELATIONSHIP_SUCCESS',
    READ_RELATIONSHIP_ERROR: 'READ_RELATIONSHIP_ERROR',
    READ_RELATIONSHIP_TIMEOUT: 'READ_RELATIONSHIP_TIMEOUT',

    UPDATE_RELATIONSHIP: 'UPDATE_RELATIONSHIP',
    UPDATE_RELATIONSHIP_SUCCESS: 'UPDATE_RELATIONSHIP_SUCCESS',
    UPDATE_RELATIONSHIP_ERROR: 'UPDATE_RELATIONSHIP_ERROR',
    UPDATE_RELATIONSHIP_TIMEOUT: 'UPDATE_RELATIONSHIP_TIMEOUT',

    DELETE_RELATIONSHIP: 'DELETE_RELATIONSHIP',
    DELETE_RELATIONSHIP_SUCCESS: 'DELETE_RELATIONSHIP_SUCCESS',
    DELETE_RELATIONSHIP_ERROR: 'DELETE_RELATIONSHIP_ERROR',
    DELETE_RELATIONSHIP_TIMEOUT: 'DELETE_RELATIONSHIP_TIMEOUT',
};

export const collaborationConstants = {};

export const notificationConstants = {
    NOTIFICATION_CLEAR_ERROR: 'NOTIFICATION_CLEAR_ERROR',

    ADD_TO_GROUP_RPC: 'AddToGroup',
    REMOVE_FROM_GROUP_RPC: 'RemoveFromGroup',

    SUBSCRIBE_PENMAN_HUB: 'SUBSCRIBE_PENMAN_HUB',
    SUBSCRIBE_PENMAN_HUB_SUCCESS: 'SUBSCRIBE_PENMAN_HUB_SUCCESS',
    SUBSCRIBE_PENMAN_HUB_ERROR: 'SUBSCRIBE_PENMAN_HUB_ERROR',
    SUBSCRIBE_PENMAN_HUB_TIMEOUT: 'SUBSCRIBE_PENMAN_HUB_TIMEOUT',

    SUBSCRIBE_GROUP: 'SUBSCRIBE_GROUP',
    SUBSCRIBE_GROUP_SUCCESS: 'SUBSCRIBE_GROUP_SUCCESS',
    SUBSCRIBE_GROUP_ERROR: 'SUBSCRIBE_GROUP_ERROR',
    SUBSCRIBE_GROUP_TIMEOUT: 'SUBSCRIBE_GROUP_TIMEOUT',

    UNSUBSCRIBE_PENMAN_HUB: 'UNSUBSCRIBE_PENMAN_HUB',
    UNSUBSCRIBE_PENMAN_HUB_SUCCESS: 'UNSUBSCRIBE_PENMAN_HUB_SUCCESS',
    UNSUBSCRIBE_PENMAN_HUB_ERROR: 'UNSUBSCRIBE_PENMAN_HUB_ERROR',
    UNSUBSCRIBE_PENMAN_HUB_TIMEOUT: 'UNSUBSCRIBE_PENMAN_HUB_TIMEOUT',

    UNSUBSCRIBE_GROUP: 'UNSUBSCRIBE_GROUP',
    UNSUBSCRIBE_GROUP_SUCCESS: 'UNSUBSCRIBE_GROUP_SUCCESS',
    UNSUBSCRIBE_GROUP_ERROR: 'UNSUBSCRIBE_GROUP_ERROR',
    UNSUBSCRIBE_GROUP_TIMEOUT: 'UNSUBSCRIBE_GROUP_TIMEOUT',

    NOTIFICATION_BOOK_CREATED: 'NOTIFICATION_BOOK_CREATED',
    NOTIFICATION_BOOK_UPDATED: 'NOTIFICATION_BOOK_UPDATED',
    NOTIFICATION_BOOK_DELETED: 'NOTIFICATION_BOOK_DELETED',

    NOTIFICATION_CHAPTER_CREATED: 'NOTIFICATION_CHAPTER_CREATED',
    NOTIFICATION_CHAPTER_UPDATED: 'NOTIFICATION_CHAPTER_UPDATED',
    NOTIFICATION_CHAPTER_DELETED: 'NOTIFICATION_CHAPTER_DELETED',

    NOTIFICATION_PERSONIFICATION_CREATED: 'NOTIFICATION_PERSONIFICATION_CREATED',
    NOTIFICATION_PERSONIFICATION_UPDATED: 'NOTIFICATION_PERSONIFICATION_UPDATED',
    NOTIFICATION_PERSONIFICATION_DELETED: 'NOTIFICATION_PERSONIFICATION_DELETED',

    NOTIFICATION_PROMPT_CREATED: 'NOTIFICATION_PROMPT_CREATED',
    NOTIFICATION_PROMPT_UPDATED: 'NOTIFICATION_PROMPT_UPDATED',
    NOTIFICATION_PROMPT_DELETED: 'NOTIFICATION_PROMPT_DELETED',

    NOTIFICATION_RELATIONSHIP_CREATED: 'NOTIFICATION_RELATIONSHIP_CREATED',
    NOTIFICATION_RELATIONSHIP_UPDATED: 'NOTIFICATION_RELATIONSHIP_UPDATED',
    NOTIFICATION_RELATIONSHIP_DELETED: 'NOTIFICATION_RELATIONSHIP_DELETED',

    NOTIFICATION_SHORT_CREATED: 'NOTIFICATION_SHORT_CREATED',
    NOTIFICATION_SHORT_UPDATED: 'NOTIFICATION_SHORT_UPDATED',
    NOTIFICATION_SHORT_DELETED: 'NOTIFICATION_SHORT_DELETED',

    NOTIFICATION_TAG_CREATED: 'NOTIFICATION_TAG_CREATED',
    NOTIFICATION_TAG_UPDATED: 'NOTIFICATION_TAG_UPDATED',
    NOTIFICATION_TAG_DELETED: 'NOTIFICATION_TAG_DELETED',

    NOTIFICATION_USER_ACTIVATED: 'NOTIFICATION_USER_ACTIVATED',
    NOTIFICATION_USER_MESSAGED: 'NOTIFICATION_USER_MESSAGED',
    NOTIFICATION_USER_CONNECTION_REQUEST: 'NOTIFICATION_USER_CONNECTION_REQUEST',
    NOTIFICATION_USER_SHARED_ENTITY: 'NOTIFICATION_USER_SHARED_ENTITY',
};

export const offlineConstants = {
    GO_OFFLINE: 'GO_OFFLINE',
    GO_ONLINE: 'GO_ONLINE',

    API_UNREACHABLE_INTERNAL_MESSAGE: 'The API is unreachable.  Queueing request to retry later.',
    API_UNREACHABLE_DISPLAY_MESSAGE: 'The API is not accessible.  Switching to offline mode.',
};
