export const baseUrl = 'https://penman.mathlander';

export const defaultDate = new Date(1970, 0, 0);

export const apiConstants = {
    ping: `${baseUrl}/api/ping`,
    usersController: `${baseUrl}/api/users`,
    promptsController: `${baseUrl}/api/prompts`,
    penmanHub: `${baseUrl}/hubs/penman`,
    timeout: 5 * 1000,
};

export const dashboardConstants = {
    VISIT_RECENT_ITEM: 'VISIT_RECENT_ITEM',
    VISIT_RECENT_ITEM_CLEAR: 'VISIT_RECENT_ITEM_CLEAR',
};

export const offlineConstants = {
    GO_OFFLINE: 'GO_OFFLINE',
    GO_ONLINE: 'GO_ONLINE',

    API_UNREACHABLE_INTERNAL_MESSAGE: 'The API is unreachable.  Queueing request to retry later.',
    API_UNREACHABLE_DISPLAY_MESSAGE: 'The API is not accessible.  Switching to offline mode.',
};

export const authConstants = {
    AUTH_LOCAL_STORAGE_KEY: 'AUTH_LOCAL_STORAGE',
    AUTH_CLEAR_ERROR: 'AUTH_CLEAR_ERROR',

    CANCEL_AUTH_ACTION: 'CANCEL_AUTH_ACTION',

    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROR',

    LOGOUT: 'LOGOUT',

    REFRESH_TOKEN: 'REFRESH_TOKEN',
    REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',
    REFRESH_TOKEN_ERROR: 'REFRESH_TOKEN_ERROR',
    REFRESH_TOKEN_TIMEOUT: 'REFRESH_TOKEN_TIMEOUT',

    CREATE_NEW_USER: 'CREATE_NEW_USER',
    CREATE_NEW_USER_SUCCESS: 'CREATE_NEW_USER_SUCCESS',
    CREATE_NEW_USER_ERROR: 'CREATE_NEW_USER_ERROR',
    CREATE_NEW_USER_TIMEOUT: 'CREATE_NEW_USER_TIMEOUT',

    UPDATE_USER_PASSWORD: 'UPDATE_USER_PASSWORD',
    UPDATE_USER_PASSWORD_SUCCESS: 'UPDATE_USER_PASSWORD_SUCCESS',
    UPDATE_USER_PASSWORD_ERROR: 'UPDATE_USER_PASSWORD_ERROR',
    UPDATE_USER_PASSWORD_TIMEOUT: 'UPDATE_USER_PASSWORD_TIMEOUT',

    UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
    UPDATE_USER_PROFILE_SUCCESS: 'UPDATE_USER_PROFILE_SUCCESS',
    UPDATE_USER_PROFILE_ERROR: 'UPDATE_USER_PROFILE_ERROR',
    UPDATE_USER_PROFILE_TIMEOUT: 'UPDATE_USER_PROFILE_TIMEOUT',

    DEACTIVATE_USER_ACCOUNT: 'DEACTIVATE_USER_ACCOUNT',
    DEACTIVATE_USER_ACCOUNT_SUCCESS: 'DEACTIVATE_USER_ACCOUNT_SUCCESS',
    DEACTIVATE_USER_ACCOUNT_ERROR: 'DEACTIVATE_USER_ACCOUNT_ERROR',
    DEACTIVATE_USER_ACCOUNT_TIMEOUT: 'DEACTIVATE_USER_ACCOUNT_TIMEOUT',
};

export const promptConstants = {
    PROMPT_LOCAL_STORAGE_KEY: 'PROMPT_LOCAL_STORAGE_KEY',
    PROMPT_CLEAR_ERROR: 'PROMPT_CLEAR_ERROR',

    CANCEL_PROMPT_ACTION: 'CANCEL_PROMPT_ACTION',

    CREATE_NEW_PROMPT: 'CREATE_NEW_PROMPT',
    CREATE_NEW_PROMPT_SUCCESS: 'CREATE_NEW_PROMPT_SUCCESS',
    CREATE_NEW_PROMPT_ERROR: 'CREATE_NEW_PROMPT_ERROR',
    CREATE_NEW_PROMPT_TIMEOUT: 'CREATE_NEW_PROMPT_TIMEOUT',

    UPDATE_PROMPT: 'UPDATE_PROMPT',
    UPDATE_PROMPT_SUCCESS: 'UPDATE_PROMPT_SUCCESS',
    UPDATE_PROMPT_ERROR: 'UPDATE_PROMPT_ERROR',
    UPDATE_PROMPT_TIMEOUT: 'UPDATE_PROMPT_TIMEOUT',

    DELETE_PROMPT: 'DELETE_PROMPT',
    DELETE_PROMPT_SUCCESS: 'DELETE_PROMPT_SUCCESS',
    DELETE_PROMPT_ERROR: 'DELETE_PROMPT_ERROR',
    DELETE_PROMPT_TIMEOUT: 'DELETE_PROMPT_TIMEOUT',

    READ_PROMPT: 'READ_PROMPT',
    READ_PROMPT_SUCCESS: 'READ_PROMPT_SUCCESS',
    READ_PROMPT_ERROR: 'READ_PROMPT_ERROR',
    READ_PROMPT_TIMEOUT: 'READ_PROMPT_TIMEOUT',

    READ_ALL_PROMPTS: 'READ_ALL_PROMPTS',
    READ_ALL_PROMPTS_SUCCESS: 'READ_ALL_PROMPTS_SUCCESS',
    READ_ALL_PROMPTS_ERROR: 'READ_ALL_PROMPTS_ERROR',
    READ_ALL_PROMPTS_TIMEOUT: 'READ_ALL_PROMPTS_TIMEOUT',
};
