CREATE USER penman WITH ENCRYPTED PASSWORD '********************';
-- GRANT ALL PRIVILEGES ON DATABASE penman TO penman;
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO penman;
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO penman;

CREATE DATABASE penman WITH
    OWNER = penman
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;
