CREATE USER penman WITH ENCRYPTED PASSWORD '****************';
GRANT ALL PRIVILEGES ON DATABASE penman to penman;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO penman;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO penman;
